version: '3.8'
services:
  # UI in react using functional component and react hooks
  ui:
    build:
      context: ./weather-prediction-ui
      dockerfile: Dockerfile-ui
    ports:
      - "5001:5001"
    networks:
      - weather-shared-network
    restart: unless-stopped

  # consul kv for secret manager
  consul:
    build:
      context: ./ssm
      dockerfile: Dockerfile-ssm
    environment:
      CONSUL_HTTP_ADDR: "consul:8500"
    container_name: consul_ssm
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./my-consul-data/:/consul/data
    networks:
      - weather-shared-network
    restart: unless-stopped

  # nginx for proxy and routing
  nginx:
    image: nginx:latest
    container_name: nginx_weather_prediction
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - api
    networks:
      - weather-shared-network
    restart: unless-stopped

  # REST API in kotlin-jvm, springboot, okhttp3
  api:
    build:
      context: ./weather-prediction-api
      dockerfile: Dockerfile-api
    ports:
      - "8080:8080"
    networks:
      - weather-shared-network
    restart: unless-stopped
    depends_on:
      - redis-cache-weather-prediction

  # Redis server for caching in api
  redis-cache-weather-prediction:
    image: "redis"
    ports:
      - "6379:6379"
    container_name: redis-cache-weather-prediction
    volumes:
      - ./my-redis-cache/:/data
    networks:
      - weather-shared-network
    restart: unless-stopped

  # Kafka Zookeeper
  kaf-zoo:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: kaf-zoo
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka Broker
  kaf-bro:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kaf-bro
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - kaf-zoo
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'kaf-zoo:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kaf-bro:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

networks:
  weather-shared-network:
