apiVersion: v1
kind: Service
metadata:
  name: consul-ssm
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8500
    targetPort: 8500
  - name: dns
    port: 8600
    targetPort: 8600
  selector:
    app: consul-ssm