apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache-weather-prediction
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache-weather-prediction
  template:
    metadata:
      labels:
        app: redis-cache-weather-prediction
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        hostPath:
          path: /data/redis