apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-ssm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-ssm
  template:
    metadata:
      labels:
        app: consul-ssm
    spec:
      containers:
      - name: consul
        image: ianunay/weather-app-ssm:v1
        ports:
        - containerPort: 8500
        - containerPort: 8600
        volumeMounts:
        - mountPath: /consul/data
          name: consul-data
      volumes:
      - name: consul-data
        hostPath:
          path: /data/consul